import { addressesXmlResponse } from "../Assets/Xml/grav.addresses.xml";
import { addressesMultipleXmlResponse } from "../Assets/Xml/grav.addresses.multiple.xml";
import { deleteUserImageXmlResponse } from "../Assets/Xml/grav.deleteUserImage.xml";
import { existsXmlResponse } from "../Assets/Xml/grav.exists.xml";
import { existsMultipleXmlResponse } from "../Assets/Xml/grav.exists.multiple.xml";
import { faultXmlResponse } from "../Assets/Xml/grav.fault.xml";
import { removeImageXmlResponse } from "../Assets/Xml/grav.removeImage.xml";
import { removeImageMultipleXmlResponse } from "../Assets/Xml/grav.removeImage.multiple.xml";
import { saveEncodedImageXmlResponse } from "../Assets/Xml/grav.saveEncodedImage.xml";
import { saveImageXmlResponse } from "../Assets/Xml/grav.saveImage.xml";
import { saveUrlXmlResponse } from "../Assets/Xml/grav.saveUrl.xml";
import { userImagesXmlResponse } from "../Assets/Xml/grav.userImages.xml";
import { useUserImageXmlResponse } from "../Assets/Xml/grav.useUserImage.xml";
import { useUserImageMultipleXmlResponse } from "../Assets/Xml/grav.useUserImage.multiple.xml";

export const addressesXml = addressesXmlResponse;
export const addressesMultipleXml = addressesMultipleXmlResponse;
export const deleteUserImageXml = deleteUserImageXmlResponse;
export const existsXml = existsXmlResponse;
export const existsMultipleXml = existsMultipleXmlResponse;
export const faultXml = faultXmlResponse;
export const removeImageXml = removeImageXmlResponse;
export const removeImageMultipleXml = removeImageMultipleXmlResponse;
export const saveEncodedImageXml = saveEncodedImageXmlResponse;
export const saveImageXml = saveImageXmlResponse;
export const saveUrlXml = saveUrlXmlResponse;
export const userImagesXml = userImagesXmlResponse;
export const useUserImageXml = useUserImageXmlResponse;
export const useUserImageMultipleXml = useUserImageMultipleXmlResponse;
