"use strict";
// export const methods: {[methodName: string]: [Function:string]; } = {
//   "grav.exists": (hash: string) => {
//     return `<methodCall>
//               <methodName>grav.exists</methodName>
//               <params>
//                 <param><value><struct>
//                   <member>
//                     <name>hashes</name>
//                     <value>
//                       <array>
//                         <data>
//                           <value>${hash}</value>
//                         </data>
//                       </array>
//                     </value>
//                   </member>
//                   <member>
//                     <name>password</name>
//                     <value>
//                       <string>${password}</string>
//                     </value>
//                   </member>
//                 </struct></value></param>
//               </params>
//             </methodCall>`;
//   }
// };
// /*
// [GRAV.EXISTS]: function(hash){
//       return `<methodCall>
//                 <methodName>grav.exists</methodName>
//                 <params>
//                   <param><value><struct>
//                     <member>
//                       <name>hashes</name>
//                       <value>
//                         <array>
//                           <data>
//                             <value>${hash}</value>
//                           </data>
//                         </array>
//                       </value>
//                     </member>
//                     <member>
//                       <name>password</name>
//                       <value>
//                         <string>${password}</string>
//                       </value>
//                     </member>
//                   </struct></value></param>
//                 </params>
//               </methodCall>`;
//     },
//     [GRAV.ADDRESSES]: function(){
//       return `<methodCall>
//                 <methodName>grav.addresses</methodName>
//                 <params>
//                   <param><value><struct>
//                     <member>
//                       <name>password</name>
//                       <value>
//                         <string>${password}</string>
//                       </value>
//                     </member>
//                   </struct></value></param>
//                 </params>
//               </methodCall>`;
//     },
//     [GRAV.USER_IMAGES]: function (){
//       return `<methodCall>
//               <methodName>grav.userimages</methodName>
//               <params>
//                 <param><value><struct>
//                   <member>
//                     <name>password</name>
//                     <value>
//                       <string>${password}</string>
//                     </value>
//                   </member>
//                 </struct></value></param>
//               </params>
//             </methodCall>`;
//     },
//     [GRAV.SAVE_URL]: function (imageUrl, rating = 0){
//       return `<methodCall>
//                 <methodName>grav.saveUrl</methodName>
//                 <params>
//                   <param><value><struct>
//                     <member>
//                       <name>url</name>
//                       <value>
//                         <string>${imageUrl}</string>
//                       </value>
//                     </member>
//                     <member>
//                       <name>rating</name>
//                       <value>
//                         <int>${rating}</int>
//                       </value>
//                     </member>
//                     <member>
//                       <name>password</name>
//                       <value>
//                         <string>${password}</string>
//                       </value>
//                     </member>
//                   </struct></value></param>
//                 </params>
//               </methodCall>`;
//     },
//     [GRAV.USE_USER_IMAGE]: function (imageName){
//       return `<methodCall>
//                 <methodName>grav.useUserimage</methodName>
//                 <params>
//                   <param><value><struct>
//                     <member>
//                       <name>userimage</name>
//                       <value>
//                         <string>${imageName}</string>
//                       </value>
//                     </member>
//                     <member>
//                       <name>addresses</name>
//                       <value>
//                         <array>
//                           <data>
//                             <value><string>${email}</string></value>
//                           </data>
//                         </array>
//                       </value>
//                     </member>
//                     <member>
//                       <name>password</name>
//                       <value>
//                         <string>${password}</string>
//                       </value>
//                     </member>
//                   </struct></value></param>
//                 </params>
//               </methodCall>`;
//     },
//     [GRAV.REMOVE_IMAGE]: function (){
//       return `<methodCall>
//               <methodName>grav.removeImage</methodName>
//               <params>
//                 <param><value><struct>
//                   <member>
//                     <name>addresses</name>
//                     <value>
//                       <array>
//                         <data>
//                           <value><string>${email}</string></value>
//                         </data>
//                       </array>
//                     </value>
//                   </member>
//                   <member>
//                     <name>password</name>
//                     <value>
//                       <string>${password}</string>
//                     </value>
//                   </member>
//                 </struct></value></param>
//               </params>
//             </methodCall>`;
//     },
//     [GRAV.DELETE_USER_IMAGE]: function (imageName){
//       return `<methodCall>
//               <methodName>grav.deleteUserimage</methodName>
//               <params>
//                 <param><value><struct>
//                   <member>
//                     <name>userimage</name>
//                     <value>
//                       <string>${imageName}</string>
//                     </value>
//                   </member>
//                   <member>
//                     <name>password</name>
//                     <value>
//                       <string>${password}</string>
//                     </value>
//                   </member>
//                 </struct></value></param>
//               </params>
//             </methodCall>`;
//     },
//     [GRAV.TEST]: function (){
// return `<methodCall>
//           <methodName>grav.test</methodName>
//           <params>
//             <param><value><struct>
//               <member>
//                 <name>password</name>
//                 <value>
//                   <string>${password}</string>
//                 </value>
//               </member>
//             </struct></value></param>
//           </params>
//         </methodCall>`;
//     },
// */
